from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
import datetime
from services.ai import generate_analyst_report # Import the text generator

class ReportGenerator:
    """
    Generates PDF Analyst Reports.
    """

    @staticmethod
    async def create_pdf_report(ticker: str) -> BytesIO:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # 1. Generate Metadata
        report_date = datetime.datetime.now().strftime("%Y-%m-%d")
        
        # 2. Get AI Content
        # We need to parse the markdown returned by AI to format it slightly better, 
        # but for now we will just dump it as paragraphs.
        ai_text = await generate_analyst_report(ticker)
        
        # Title
        title_style = styles['Title']
        title_style.textColor = colors.darkblue
        story.append(Paragraph(f"Analyst Report: {ticker}", title_style))
        story.append(Paragraph(f"Date: {report_date} | Source: QuantDash AI", styles['Normal']))
        story.append(Spacer(1, 24))
        
        # Branding Line
        story.append(Paragraph("__________________________________________________________________", styles['Normal']))
        story.append(Spacer(1, 24))
        
        # Content Processing
        # Split by newlines and create paragraphs
        lines = ai_text.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 12))
                continue
                
            if line.startswith('# '):
                # H1 (Already handled by Title mostly, but just in case)
                story.append(Paragraph(line.replace('# ', ''), styles['Heading1']))
            elif line.startswith('## '):
                # H2
                story.append(Paragraph(line.replace('## ', ''), styles['Heading2']))
            elif line.startswith('### '):
                # H3
                story.append(Paragraph(line.replace('### ', ''), styles['Heading3']))
            elif line.startswith('*') or line.startswith('-'):
                # Bullet points
                story.append(Paragraph(f"• {line[1:].strip()}", styles['Normal']))
            else:
                # Normal text
                story.append(Paragraph(line, styles['Normal']))
                
        # Disclaimer
        story.append(Spacer(1, 48))
        disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)
        story.append(Paragraph("DISCLAIMER: This report is generated by AI for informational purposes only. It does not constitute financial advice. Do Your Own Research.", disclaimer_style))

        doc.build(story)
        buffer.seek(0)
        return buffer
