"use client";

import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ShieldCheck, ArrowLeft } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-white font-sans selection:bg-cyan-500/30 selection:text-cyan-200 overflow-hidden relative">
      {/* Background Ambient Glow */}
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(124,58,237,0.08),transparent_45%)]" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_15%,rgba(6,182,212,0.08),transparent_45%)]" />
        <div className="absolute inset-0 bg-gradient-to-b from-slate-950/90 via-slate-950/85 to-slate-950/95" />
      </div>

      {/* Navbar */}
      <nav className="relative z-50 border-b border-white/5 bg-[rgba(8,10,20,0.7)] backdrop-blur-xl sticky top-0 transition-all duration-300">
        <div className="max-w-7xl mx-auto px-6 h-24 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group cursor-pointer">
            <div className="relative h-16 w-48">
              <Image 
                src="/quantdash_logo.png" 
                alt="QuantDash" 
                fill 
                className="object-contain mix-blend-lighten hover:brightness-110 transition-all" 
                style={{ filter: 'contrast(1.5)' }} 
              />
            </div>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/" className="text-sm font-medium text-slate-400 hover:text-cyan-400 transition-colors tracking-wide flex items-center gap-2">
              <ArrowLeft size={14} />
              <span>Back to Home</span>
            </Link>
            <Link
              href="/dashboard"
              className="px-6 py-2.5 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white text-xs font-bold rounded-xl transition-all shadow-[0_0_20px_-5px_rgba(6,182,212,0.5)] hover:shadow-[0_0_25px_-5px_rgba(6,182,212,0.7)]"
            >
              Launch Terminal
            </Link>
          </div>
        </div>
      </nav>

      {/* Content Container */}
      <div className="relative z-10 max-w-4xl mx-auto px-6 py-20">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-black mb-4 tracking-tight">
            Privacy <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">Policy</span>
          </h1>
          <p className="text-slate-400 text-sm">
            Last Updated: May 25, 2026
          </p>
        </div>

        <div className="glass-panel p-8 md:p-12 border-t border-cyan-500/20 shadow-2xl">
          
          <div className="flex flex-col md:flex-row gap-5 bg-cyan-500/5 border border-cyan-500/25 rounded-2xl p-6 mb-8">
            <div className="p-2 bg-cyan-500/10 rounded-xl shrink-0 h-fit w-fit">
              <ShieldCheck size={28} className="text-cyan-400" />
            </div>
            <div>
              <h3 className="text-cyan-400 font-bold text-lg mb-2">Committed to Data Minimization</h3>
              <p className="text-slate-200 text-sm leading-relaxed">
                Ry Quant values your privacy. We do not require account registration or store sensitive financial details. All analysis, models, and custom portfolio layouts are run and stored locally inside your browser unless you explicitly submit feedback.
              </p>
            </div>
          </div>

          <div className="space-y-8 text-slate-300 text-sm md:text-base leading-relaxed">
            
            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. Information We Collect</h2>
              <p className="mb-3">
                We collect information to optimize the platform experience, troubleshoot technical issues, and gauge user feedback. This includes:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Local Browser Storage:</strong> Custom simulation settings, selected stock tickers, and UI theme states are saved directly on your device via LocalStorage or cookies.</li>
                <li><strong>System Logs & Diagnostics:</strong> Anonymous technical logs generated by server requests (IP addresses, request latency, system stability).</li>
                <li><strong>Feedback Data:</strong> Any text messages, metrics, or logs you choose to submit via our Feedback forms.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. How We Use Information</h2>
              <p className="mb-3">
                Information is utilized solely for operational improvement:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Analyzing performance stats and caching tickers to minimize system latency.</li>
                <li>Addressing bug reports and fixing UI/UX glitches.</li>
                <li>Assessing what modules (e.g. Greeks Lab, Backtester) are most popular to prioritize updates.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. Third-Party Integrations</h2>
              <p>
                Our services are hosted on Vercel, which collects standard web traffic logs. We also integrate Vercel Web Analytics to monitor performance. We do not share, sell, or rent user data to third-party advertising services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">4. Security</h2>
              <p>
                We use industry-standard HTTPS encryption to encrypt data in transit. However, please be aware that no storage or communication system is entirely secure. We encourage you to test simulated strategies without using real portfolio keys.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">5. User Control</h2>
              <p>
                You can delete your saved preferences, settings, and cached tickers at any time by clearing your browser cache and cookies for this domain.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">6. Contact Information</h2>
              <p>
                For questions regarding data practices, you can reach out to the founders at <a href="mailto:info@ryquant.com" className="text-cyan-400 hover:underline">info@ryquant.com</a>.
              </p>
            </section>

          </div>

          <div className="border-t border-white/5 pt-8 mt-10 text-center text-xs text-slate-500">
            <p>
              By continuing to use QuantDash, you consent to our collection and usage of anonymized data as described in this policy.
            </p>
          </div>

        </div>
      </div>

      {/* Footer */}
      <footer className="relative z-10 py-12 text-center text-slate-600 text-sm border-t border-white/5 mt-20">
        <p>© {new Date().getFullYear()} Ry Quant. All rights reserved.</p>
        <p className="mt-2 text-xs opacity-50">QuantDash™ is a trademark of Ry Quant.</p>
      </footer>
    </div>
  );
}
