import {
    Building2,
    FileText,
    Calculator,
    Landmark,
    TrendingUp,
    BarChart3,
    Globe,
    Target,
    PiggyBank,
    Users,
    Home,
    BookOpen,
    Gavel,
    LineChart,
    Briefcase,
    PieChart,
    DollarSign,
    Wallet,
    Building,
    LucideIcon
} from 'lucide-react';

export interface LibraryTopic {
    id: string;
    title: string;
    icon: LucideIcon;
    description: string;
    category: string;
    difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
    tags: string[];
    relatedTopics?: string[];
    terms: {
        term: string;
        definition: string;
        example?: string;
    }[];
}

export const LIBRARY_TOPICS: LibraryTopic[] = [
    {
        id: 'corporate-finance',
        title: 'Corporate Finance',
        icon: Building2,
        description: 'Managing capital structure, funding and financial decisions.',
        category: 'Finance',
        difficulty: 'Intermediate',
        tags: ['Corporate', 'Finance', 'Capital', 'Investment'],
        relatedTopics: ['financial-management', 'financial-modeling', 'private-equity'],
        terms: [
            { term: 'WACC', definition: 'Weighted Average Cost of Capital - the average rate a company expects to pay to finance its assets.', example: 'If a company has 60% equity at 10% cost and 40% debt at 5% cost, WACC = (0.6 × 0.10) + (0.4 × 0.05) = 8%' },
            { term: 'NPV', definition: 'Net Present Value - the difference between the present value of cash inflows and outflows.', example: 'A project requiring $100k upfront that generates $120k in present value terms has NPV = $20k' },
            { term: 'IRR', definition: 'Internal Rate of Return - the expected compound annual rate of return that will be earned on a project or investment.', example: 'If you invest $1000 today and receive $1210 in 2 years, IRR ≈ 10% annually' },
            { term: 'Capital Budgeting', definition: 'The process of planning and managing a firm\'s long-term investments in assets.', example: 'A company evaluating whether to build a new factory by calculating NPV and IRR' },
            { term: 'Free Cash Flow', definition: 'Cash generated by operations after accounting for capital expenditures.', example: 'Operating Cash Flow of $500M minus CapEx of $200M = FCF of $300M' },
            { term: 'Capital Structure', definition: 'Mix of debt and equity that a company uses to finance its operations.', example: 'A company with $60M debt and $40M equity has a 60/40 capital structure' },
            { term: 'Dividend Policy', definition: 'Guidelines a company uses to decide how much money to return to shareholders.', example: 'Apple maintaining a 15% payout ratio while investing heavily in R&D' },
            { term: 'Merger & Acquisition', definition: 'Strategic decision where one company purchases or combines with another.', example: 'Disney acquiring 21st Century Fox for $71 billion in 2019' },
            { term: 'Leverage Ratio', definition: 'Measure of a company\'s debt relative to its equity or assets.', example: 'Debt-to-Equity ratio of 2.0 means $2 of debt for every $1 of equity' }
        ]
    },
    {
        id: 'financial-accounting',
        title: 'Financial Accounting',
        icon: FileText,
        description: 'Reporting financial information to external users.',
        category: 'Accounting',
        difficulty: 'Beginner',
        tags: ['Accounting', 'GAAP', 'Financial Statements'],
        relatedTopics: ['accounting-principles', 'managerial-accounting', 'financial-statement-analysis'],
        terms: [
            { term: 'GAAP', definition: 'Generally Accepted Accounting Principles - standard accounting rules used in the US.', example: 'Companies must recognize revenue when earned, not when cash is received (accrual basis)' },
            { term: 'Accrual Basis', definition: 'Method of recording accounting transactions for revenue when earned and expenses when incurred.', example: 'Recording a sale in December even though payment arrives in January' },
            { term: 'Balance Sheet', definition: 'Financial statement showing assets, liabilities, and shareholders\' equity at a specific point in time.', example: 'Assets ($500k) = Liabilities ($300k) + Equity ($200k)' },
            { term: 'Income Statement', definition: 'Financial statement showing revenues, expenses, and profit over a period of time.', example: 'Revenue ($1M) - Expenses ($700k) = Net Income ($300k)' },
            { term: 'Cash Flow Statement', definition: 'Shows how changes in balance sheet and income affect cash through operating, investing, and financing activities.', example: 'Net income of $100k plus depreciation of $20k minus inventory increase of $10k = operating cash flow of $110k' },
            { term: 'Depreciation', definition: 'Systematic allocation of a tangible asset\'s cost over its useful life.', example: 'A $100k machine with 10-year life has annual depreciation of $10k (straight-line)' },
            { term: 'Double-Entry Bookkeeping', definition: 'Every transaction affects at least two accounts with equal debits and credits.', example: 'Buying inventory for $1000 cash: Debit Inventory $1000, Credit Cash $1000' },
            { term: 'Accounts Receivable', definition: 'Money owed to a company by customers for goods/services provided on credit.', example: 'Selling $50k worth of products with net-30 terms creates $50k in A/R' },
            { term: 'Goodwill', definition: 'Intangible asset arising when a company acquires another for more than fair value of net assets.', example: 'Buying a company with $100M assets for $150M creates $50M goodwill' }
        ]
    },
    {
        id: 'financial-management',
        title: 'Financial Management',
        icon: Calculator,
        description: 'Strategic planning, organizing, directing, and controlling of financial undertakings.',
        category: 'Finance',
        difficulty: 'Intermediate',
        tags: ['Management', 'Working Capital', 'Cash Flow'],
        relatedTopics: ['corporate-finance', 'managerial-accounting'],
        terms: [
            { term: 'Working Capital', definition: 'The difference between a company\'s current assets and current liabilities.', example: 'Current Assets of $500k minus Current Liabilities of $300k = $200k Working Capital' },
            { term: 'Cash Conversion Cycle', definition: 'Time it takes to convert inventory and receivables into cash.', example: 'Days Inventory Outstanding (60) + Days Sales Outstanding (30) - Days Payable Outstanding (45) = 45 days' },
            { term: 'Liquidity Management', definition: 'Ensuring sufficient cash is available to meet short-term obligations.', example: 'Maintaining a $1M cash reserve to cover unexpected expenses' },
            { term: 'Credit Policy', definition: 'Guidelines for extending credit to customers and collecting receivables.', example: 'Offering net-30 terms to AAA-rated clients, net-15 for others' },
            { term: 'Inventory Turnover', definition: 'How many times inventory is sold and replaced over a period.', example: 'Cost of Goods Sold ($1.2M) ÷ Average Inventory ($300k) = 4 turns per year' },
            { term: 'Days Sales Outstanding', definition: 'Average number of days it takes to collect payment after a sale.', example: '(Accounts Receivable / Revenue) × 365 = DSO' },
            { term: 'Cash Budget', definition: 'Detailed projection of cash receipts and disbursements over a period.', example: 'Forecasting monthly cash needs to ensure no shortfalls occur' }
        ]
    },
    {
        id: 'banking-finance',
        title: 'Banking & Finance',
        icon: Landmark,
        description: 'Study of financial institutions and markets.',
        category: 'Banking',
        difficulty: 'Intermediate',
        tags: ['Banking', 'Lending', 'Interest Rates'],
        relatedTopics: ['financial-market', 'macroeconomics'],
        terms: [
            { term: 'Spread', definition: 'The difference between the interest rate a bank pays to depositors and the interest rate it receives from loans.', example: 'Bank pays 2% on deposits, charges 6% on loans = 4% spread' },
            { term: 'Fractional Reserve Banking', definition: 'System where banks hold only a fraction of deposits as reserves.', example: 'With 10% reserve requirement, $1000 deposit allows $900 in new loans' },
            { term: 'Capital Adequacy Ratio', definition: 'Measure of a bank\'s capital relative to its risk-weighted assets.', example: 'Basel III requires Tier 1 capital to be at least 6% of risk-weighted assets' },
            { term: 'Non-Performing Loan', definition: 'Loan in which the borrower is not making principal or interest payments.', example: 'A mortgage where payments haven\'t been made for 90+ days' },
            { term: 'Prime Rate', definition: 'Interest rate commercial banks charge their most creditworthy customers.', example: 'If prime is 8%, a customer might get prime + 2% = 10% on a loan' },
            { term: 'Interbank Lending Rate', definition: 'Interest rate charged on short-term loans between banks.', example: 'LIBOR (being replaced by SOFR) was the benchmark for trillions in contracts' },
            { term: 'Deposit Insurance', definition: 'Protection provided to depositors in case of bank failure.', example: 'FDIC insures deposits up to $250,000 per depositor per bank' },
            { term: 'Loan-to-Value Ratio', definition: 'Ratio of a loan to the value of the asset purchased.', example: 'Buying a $500k house with $100k down = 80% LTV ($400k loan)' }
        ]
    },
    {
        id: 'financial-market',
        title: 'Financial Market',
        icon: TrendingUp,
        description: 'Marketplace for trading financial assets.',
        category: 'Markets',
        difficulty: 'Intermediate',
        tags: ['Trading', 'Markets', 'Liquidity'],
        relatedTopics: ['investments', 'banking-finance'],
        terms: [
            { term: 'Liquidity', definition: 'How easily an asset can be bought or sold without affecting its price.', example: 'Large-cap stocks like Apple are more liquid than penny stocks' },
            { term: 'Bid-Ask Spread', definition: 'Difference between the highest price a buyer will pay (bid) and lowest price a seller will accept (ask).', example: 'Stock with bid $100.00 and ask $100.05 has a $0.05 spread' },
            { term: 'Market Maker', definition: 'Firm that stands ready to buy and sell a particular stock on a regular and continuous basis.', example: 'Citadel Securities providing liquidity for thousands of stocks' },
            { term: 'Short Selling', definition: 'Selling borrowed securities with the intent to buy them back at a lower price.', example: 'Borrowing 100 shares at $50, selling for $5000, buying back at $40 for profit of $1000' },
            { term: 'Circuit Breaker', definition: 'Trading halt triggered when markets fall by a predetermined percentage.', example: 'NYSE halts trading for 15 min if S&P 500 falls 7% from previous close' },
            { term: 'Margin Call', definition: 'Demand by a broker for an investor to deposit additional money or securities.', example: 'When portfolio value falls below maintenance margin requirement' },
            { term: 'Volume', definition: 'Number of shares or contracts traded in a security or market during a given period.', example: 'Apple trading 100 million shares in one day' },
            { term: 'Market Capitalization', definition: 'Total value of a company\'s outstanding shares.', example: 'Company with 1 billion shares at $50 = $50 billion market cap' }
        ]
    },
    {
        id: 'financial-statement-analysis',
        title: 'Statement Analysis',
        icon: BarChart3,
        description: 'Analyzing a company\'s financial statements for decision-making.',
        category: 'Accounting',
        difficulty: 'Advanced',
        tags: ['Analysis', 'Ratios', 'Financial Statements'],
        relatedTopics: ['financial-accounting', 'quantitative-analysis'],
        terms: [
            { term: 'Horizontal Analysis', definition: 'Comparison of historical financial information over a series of reporting periods.', example: 'Revenue growing from $100M (2022) to $120M (2023) = 20% growth' },
            { term: 'Vertical Analysis', definition: 'Expressing each line item as a percentage of a base figure.', example: 'Cost of Goods Sold as 60% of Revenue' },
            { term: 'Common Size Statement', definition: 'Financial statement where all items are expressed as percentages.', example: 'Income statement showing COGS as 60%, SG&A as 20%, Net Income as 15% of revenue' },
            { term: 'Trend Analysis', definition: 'Method of identifying patterns by comparing data over multiple periods.', example: 'Analyzing 5 years of revenue growth to identify acceleration or deceleration' },
            { term: 'Ratio Analysis', definition: 'Quantitative analysis using financial ratios to evaluate various aspects of performance.', example: 'Using P/E, ROE, and debt ratios to compare companies' },
            { term: 'DuPont Analysis', definition: 'Breaking down ROE into profit margin, asset turnover, and financial leverage.', example: 'ROE = (Net Income/Sales) × (Sales/Assets) × (Assets/Equity)' },
            { term: 'Quality of Earnings', definition: 'Degree to which earnings are sustainable and reflect true economic performance.', example: 'High accruals relative to cash flow may indicate lower quality earnings' }
        ]
    },
    {
        id: 'macroeconomics',
        title: 'Macroeconomics',
        icon: Globe,
        description: 'Performance, structure, behavior, and decision-making of an economy as a whole.',
        category: 'Economics',
        difficulty: 'Intermediate',
        tags: ['Economics', 'GDP', 'Monetary Policy'],
        relatedTopics: ['microeconomics', 'international-finance', 'economics'],
        terms: [
            { term: 'GDP', definition: 'Gross Domestic Product - total value of goods and services produced within a country.', example: 'US GDP of $25 trillion means all economic output adds up to that value' },
            { term: 'Inflation', definition: 'The rate at which prices for goods and services rise.', example: 'CPI increasing from 100 to 103 = 3% annual inflation' },
            { term: 'Monetary Policy', definition: 'Actions by a central bank to influence money supply and interest rates.', example: 'Federal Reserve raising interest rates to combat inflation' },
            { term: 'Fiscal Policy', definition: 'Government\'s use of taxation and spending to influence the economy.', example: 'Increasing government spending during recession to stimulate growth' },
            { term: 'Unemployment Rate', definition: 'Percentage of labor force that is jobless and actively seeking employment.', example: '5% unemployment rate means 5 out of 100 workers are unemployed' },
            { term: 'Phillips Curve', definition: 'Inverse relationship between inflation and unemployment.', example: 'Lower unemployment often leads to higher inflation due to wage pressure' },
            { term: 'Quantitative Easing', definition: 'Central bank purchasing government bonds to inject money into the economy.', example: 'Fed buying $120B/month in bonds during COVID-19 pandemic' },
            { term: 'Consumer Price Index', definition: 'Measure of average change in prices paid by consumers for market basket of goods.', example: 'CPI tracking prices of food, housing, healthcare, transportation' },
            { term: 'Trade Balance', definition: 'Difference between a country\'s exports and imports.', example: 'Exports of $200B minus imports of $300B = -$100B trade deficit' }
        ]
    },
    {
        id: 'international-finance',
        title: 'International Finance',
        icon: Globe,
        description: 'Monetary interactions between two or more countries.',
        category: 'Finance',
        difficulty: 'Advanced',
        tags: ['Currency', 'Exchange Rates', 'Global Finance'],
        relatedTopics: ['macroeconomics', 'banking-finance'],
        terms: [
            { term: 'Exchange Rate', definition: 'The value of one currency for the purpose of conversion to another.', example: 'EUR/USD = 1.10 means 1 euro equals $1.10' },
            { term: 'Purchasing Power Parity', definition: 'Theory that exchange rates should equalize the purchasing power of different currencies.', example: 'Big Mac costing $5 in US and £4 in UK suggests GBP/USD should be 1.25' },
            { term: 'Foreign Exchange Risk', definition: 'Risk of loss from changes in currency exchange rates.', example: 'US company importing from Europe loses money if euro strengthens' },
            { term: 'Currency Hedging', definition: 'Using financial instruments to reduce exposure to exchange rate fluctuations.', example: 'Using forward contracts to lock in exchange rate for future payment' },
            { term: 'Balance of Payments', definition: 'Record of all economic transactions between residents of a country and the rest of the world.', example: 'Current account + capital account + financial account = 0' },
            { term: 'Hot Money', definition: 'Funds that rapidly move between countries seeking highest short-term returns.', example: 'Investors pulling money from emerging markets during uncertainty' },
            { term: 'Carry Trade', definition: 'Borrowing in low interest rate currency to invest in high interest rate currency.', example: 'Borrowing yen at 0.1% to buy Australian dollars yielding 4%' }
        ]
    },
    {
        id: 'microeconomics',
        title: 'Microeconomics',
        icon: Target,
        description: 'Behavior of individuals and firms in making decisions.',
        category: 'Economics',
        difficulty: 'Beginner',
        tags: ['Microeconomics', 'Supply', 'Demand', 'Market Forces'],
        relatedTopics: ['macroeconomics', 'economics'],
        terms: [
            { term: 'Elasticity', definition: 'A measure of a variable\'s sensitivity to a change in another variable.', example: 'If 10% price increase causes 20% decrease in demand, elasticity = -2' },
            { term: 'Supply and Demand', definition: 'Economic model determining price in a market based on quantity supplied and demanded.', example: 'High demand + low supply = higher prices (PS5 shortage in 2020)' },
            { term: 'Marginal Cost', definition: 'Additional cost of producing one more unit of a good.', example: 'If total cost increases from $1000 to $1080 when output goes from 100 to 101, MC = $80' },
            { term: 'Consumer Surplus', definition: 'Difference between what consumers are willing to pay and what they actually pay.', example: 'Willing to pay $100 for concert ticket but only paying $60 = $40 surplus' },
            { term: 'Economies of Scale', definition: 'Cost advantages gained by increasing production scale.', example: 'Fixed costs of $1M spread over 10k units = $100/unit vs 1k units = $1000/unit' },
            { term: 'Perfect Competition', definition: 'Market structure with many buyers and sellers of identical products.', example: 'Agricultural commodities like wheat where no single seller can influence price' },
            { term: 'Monopoly', definition: 'Market structure with single seller of a good with no close substitutes.', example: 'Local utility company being sole provider of electricity' },
            { term: 'Price Discrimination', definition: 'Charging different prices to different customers for the same product.', example: 'Airlines charging higher fares for last-minute bookings' }
        ]
    },
    {
        id: 'investments',
        title: 'Investments',
        icon: PiggyBank,
        description: 'Allocation of money with the expectation of a positive benefit/return.',
        category: 'Investing',
        difficulty: 'Intermediate',
        tags: ['Investing', 'Portfolio', 'Risk Management'],
        relatedTopics: ['investment-management', 'portfolio-management', 'financial-market'],
        terms: [
            { term: 'Diversification', definition: 'Risk management strategy that mixes a wide variety of investments within a portfolio.', example: 'Holding stocks, bonds, real estate, and commodities instead of just stocks' },
            { term: 'Beta', definition: 'Measure of a stock\'s volatility in relation to the overall market.', example: 'Beta of 1.5 means stock moves 1.5% for every 1% move in market' },
            { term: 'Sharpe Ratio', definition: 'Measure of risk-adjusted return calculated as excess return per unit of volatility.', example: '(Portfolio Return 12% - Risk Free Rate 3%) / Volatility 15% = Sharpe of 0.6' },
            { term: 'Modern Portfolio Theory', definition: 'Investment approach that seeks to maximize return for a given level of risk.', example: 'Combining assets with low correlation to reduce portfolio volatility' },
            { term: 'Efficient Market Hypothesis', definition: 'Theory that asset prices reflect all available information.', example: 'Claiming you can\'t consistently beat the market without inside information' },
            { term: 'Value Investing', definition: 'Investment strategy of buying undervalued securities based on fundamental analysis.', example: 'Warren Buffett buying companies trading below intrinsic value' },
            { term: 'Growth Investing', definition: 'Strategy focusing on companies expected to grow earnings faster than average.', example: 'Investing in tech startups with high revenue growth but no current profits' },
            { term: 'Dollar-Cost Averaging', definition: 'Investing fixed amounts at regular intervals regardless of price.', example: 'Investing $500/month into S&P 500 index fund regardless of market level' }
        ]
    },
    {
        id: 'management-communication',
        title: 'Management Comm.',
        icon: Users,
        description: 'Communication within an organization.',
        category: 'Business',
        difficulty: 'Beginner',
        tags: ['Communication', 'Corporate Governance', 'Leadership'],
        relatedTopics: ['organizational-behavior'],
        terms: [
            { term: 'Stakeholder', definition: 'A party that has an interest in a company and can either affect or be affected by the business.', example: 'Shareholders, employees, customers, suppliers, and communities' },
            { term: 'Corporate Governance', definition: 'System of rules, practices, and processes directing and controlling a company.', example: 'Board of directors overseeing management on behalf of shareholders' },
            { term: 'Financial Disclosure', definition: 'Providing relevant financial information to stakeholders.', example: 'Filing quarterly 10-Q and annual 10-K reports with the SEC' },
            { term: 'Investor Relations', definition: 'Corporate function responsible for communication between management and investors.', example: 'Hosting quarterly earnings calls to discuss financial results' },
            { term: 'Management Discussion & Analysis', definition: 'Section of annual report where management discusses company performance.', example: 'Explaining revenue growth drivers and future outlook in 10-K' },
            { term: 'Earnings Guidance', definition: 'Management\'s forecast of future financial performance.', example: 'Company projecting Q4 EPS between $1.50-$1.60' }
        ]
    },
    {
        id: 'real-estate',
        title: 'Real Estate',
        icon: Home,
        description: 'Property consisting of land and the buildings on it.',
        category: 'Real Estate',
        difficulty: 'Intermediate',
        tags: ['Real Estate', 'Property', 'REITs'],
        relatedTopics: ['investments', 'taxation'],
        terms: [
            { term: 'REIT', definition: 'Real Estate Investment Trust - a company that owns, operates, or finances income-generating real estate.', example: 'Simon Property Group owning shopping malls and distributing 90%+ income as dividends' },
            {
                term: 'Cap Rate', definition: 'Capitalization Rate - rate of return on real estate investment based on net operating income.', example: 'Property generating $100k NOI worth $1M has 10% cap rate'
            },
            { term: 'Gross Rent Multiplier', definition: 'Price of property divided by gross annual rental income.', example: 'Property priced at $600k with $50k annual rent = GRM of 12' },
            { term: 'Net Operating Income', definition: 'Revenue from property minus operating expenses (excluding debt service).', example: 'Rental income $150k - expenses $50k = $100k NOI' },
            { term: 'Cash-on-Cash Return', definition: 'Annual pre-tax cash flow divided by total cash invested.', example: 'Invest $100k, receive $8k annual cash flow = 8% cash-on-cash return' },
            { term: '1031 Exchange', definition: 'Tax-deferred exchange of like-kind real estate properties.', example: 'Selling rental property and buying another within 180 days to defer capital gains' },
            { term: 'Amortization', definition: 'Gradual reduction of debt through scheduled principal payments.', example: '30-year mortgage with monthly payments reducing principal balance' }
        ]
    },
    {
        id: 'taxation',
        title: 'Taxation',
        icon: FileText,
        description: 'System of raising money to finance government.',
        category: 'Tax',
        difficulty: 'Intermediate',
        tags: ['Taxation', 'Tax Planning', 'IRS'],
        relatedTopics: ['accounting-principles', 'financial-accounting'],
        terms: [
            { term: 'Capital Gains Tax', definition: 'Tax on the profit realized on the sale of a non-inventory asset.', example: 'Buying stock at $50, selling at $100 creates $50 taxable gain' },
            { term: 'Progressive Tax', definition: 'Tax system where the tax rate increases as the taxable amount increases.', example: 'Federal income tax with brackets at 10%, 12%, 22%, 24%, 32%, 35%, 37%' },
            { term: 'Tax Loss Harvesting', definition: 'Selling securities at a loss to offset capital gains tax liability.', example: 'Offsetting $10k stock gain with $10k bond loss to reduce taxes' },
            { term: 'Marginal Tax Rate', definition: 'Tax rate applied to the last dollar of income.', example: 'Earning $90k with 22% bracket means next dollar earned taxed at 22%' },
            { term: 'Effective Tax Rate', definition: 'Average rate at which income is taxed.', example: 'Paying $20k tax on $100k income = 20% effective rate' },
            { term: 'Standard Deduction', definition: 'Fixed dollar  amount that reduces the income subject to tax.', example: '$13,850 for single filers in 2023, reducing taxable income' },
            { term: 'Qualified Dividend', definition: 'Dividends taxed at favorable long-term capital gains rates.', example: 'Dividends from US companies held 60+ days taxed at 0%, 15%, or 20% vs ordinary income rates' }
        ]
    },
    {
        id: 'accounting-principles',
        title: 'Accounting Principles',
        icon: BookOpen,
        description: 'Foundational rules of accounting.',
        category: 'Accounting',
        difficulty: 'Beginner',
        tags: ['Accounting', 'GAAP', 'Principles'],
        relatedTopics: ['financial-accounting', 'managerial-accounting'],
        terms: [
            { term: 'Matching Principle', definition: 'Requirement that expenses be reported in the same period as the revenues they helped generate.', example: 'Recording cost of goods sold in same month as sales revenue' },
            { term: 'Revenue Recognition', definition: 'Principle determining when revenue is recorded in financial statements.', example: 'Software company recognizing subscription revenue monthly as service is delivered' },
            { term: 'Conservatism Principle', definition: 'When in doubt, accountants should err on the side of caution.', example: 'Recognizing potential losses immediately but gains only when realized' },
            { term: 'Going Concern', definition: 'Assumption that entity will continue operating for the foreseeable future.', example: 'Valuing assets at historical cost rather than liquidation value' },
            { term: 'Materiality', definition: 'Information is material if its omission or misstatement could influence economic decisions.', example: '$100 error immaterial for billion-dollar company but material for $10k company' },
            { term: 'Consistency Principle', definition: 'Using same accounting methods from period to period.', example: 'Continuing to use FIFO inventory method once adopted' }
        ]
    },
    {
        id: 'business-ethics',
        title: 'Business Ethics',
        icon: Gavel,
        description: 'Moral principles playing a role in business activity.',
        category: 'Business',
        difficulty: 'Beginner',
        tags: ['Ethics', 'CSR', 'Compliance'],
        relatedTopics: ['management-communication'],
        terms: [
            { term: 'CSR', definition: 'Corporate Social Responsibility - a business model that helps a company be socially accountable.', example: 'Patagonia donating 1% of sales to environmental causes' },
            { term: 'Fiduciary Duty', definition: 'Legal obligation to act in the best interest of another party.', example: 'Board of directors acting in shareholders\' best interests' },
            { term: 'Insider Trading', definition: 'Illegal practice of trading securities based on non-public, material information.', example: 'CEO selling shares after learning of bad earnings before public announcement' },
            { term: 'Whistleblowing', definition: 'Reporting illegal or unethical behavior within an organization.', example: 'Enron employees exposing accounting fraud' },
            { term: 'Conflict of Interest', definition: 'Situation where personal interests might compromise professional judgment.', example: 'Auditor owning stock in company they audit' },
            { term: 'Corporate Accountability', definition: 'Holding corporations responsible for their actions.', example: 'Shareholders suing management for breach of fiduciary duty' }
        ]
    },
    {
        id: 'economics',
        title: 'Economics',
        icon: LineChart,
        description: 'Social science that studies the production, distribution, and consumption of goods and services.',
        category: 'Economics',
        difficulty: 'Beginner',
        tags: ['Economics', 'Cost-Benefit', 'Trade'],
        relatedTopics: ['macroeconomics', 'microeconomics'],
        terms: [
            { term: 'Opportunity Cost', definition: 'The loss of potential gain from other alternatives when one alternative is chosen.', example: 'Choosing to go to college means giving up 4 years of potential earnings' },
            { term: 'Absolute Advantage', definition: 'Ability to produce more of a good using the same resources.', example: 'Country A producing 100 cars vs Country B producing 50 with same inputs' },
            { term: 'Comparative Advantage', definition: 'Ability to produce a good at a lower opportunity cost.', example: 'Country specializing in what it produces most efficiently relative to alternatives' },
            { term: 'Laffer Curve', definition: 'Relationship between tax rates and tax revenue showing optimal rate.', example: 'Very high tax rates may reduce revenue due to decreased economic activity' },
            { term: 'Moral Hazard', definition: 'When one party takes risks because another party bears the cost.', example: 'Banks taking excessive risks knowing government will bail them out' },
            { term: 'Adverse Selection', definition: 'When one party has more information than another, leading to poor outcomes.', example: 'Sick people more likely to buy health insurance than healthy people' }
        ]
    },
    {
        id: 'investment-management',
        title: 'Investment Mgmt',
        icon: Briefcase,
        description: 'Professional asset management of various securities.',
        category: 'Investing',
        difficulty: 'Advanced',
        tags: ['Asset Management', 'Alpha', 'Performance'],
        relatedTopics: ['investments', 'portfolio-management'],
        terms: [
            { term: 'Alpha', definition: 'Measure of performance on a risk-adjusted basis - excess return relative to benchmark.', example: 'Fund returning 15% when market returned 10% has 5% alpha' },
            { term: 'Active Management', definition: 'Attempting to outperform the market through stock selection and timing.', example: 'Hedge fund manager picking individual stocks instead of buying index' },
            { term: 'Passive Management', definition: 'Investment strategy that tracks a market index.', example: 'Vanguard S&P 500 index fund mirroring market performance' },
            { term: 'Rebalancing', definition: 'Realigning portfolio weights back to target allocation.', example: 'Selling stocks after rally to return to 60/40 stock/bond allocation' },
            { term: 'Performance Attribution', definition: 'Analyzing sources of portfolio returns.', example: 'Breaking down returns into asset allocation, security selection, and timing effects' },
            { term: 'Benchmark', definition: 'Standard against which investment performance is measured.', example: 'US large-cap fund using S&P 500 as benchmark' }
        ]
    },
    {
        id: 'managerial-accounting',
        title: 'Managerial Acct.',
        icon: Calculator,
        description: 'Accounting for internal use by management.',
        category: 'Accounting',
        difficulty: 'Intermediate',
        tags: ['Managerial Accounting', 'Cost Analysis', 'Budgeting'],
        relatedTopics: ['financial-accounting', 'accounting-principles'],
        terms: [
            { term: 'Cost Center', definition: 'A department or other unit within an organization to which costs may be charged.', example: 'IT department tracked separately to monitor technology spending' },
            { term: 'Contribution Margin', definition: 'Sales revenue minus variable costs.', example: 'Selling price $50 - variable costs $30 = $20 contribution margin per unit' },
            { term: 'Break-Even Analysis', definition: 'Determining sales volume needed to cover all costs.', example: 'Fixed costs $100k ÷ contribution margin $20 = 5,000 units to break even' },
            { term: 'Variance Analysis', definition: 'Comparing actual results to budgeted amounts.', example: 'Investigating why actual costs were $10k over budget' },
            { term: 'Activity-Based Costing', definition: 'Allocating overhead costs based on activities that drive costs.', example: 'Assigning setup costs based on number of production runs, not just units' },
            { term: 'Transfer Pricing', definition: 'Price charged when divisions within a company transact.', example: 'Manufacturing division charging sales division for products' }
        ]
    },
    {
        id: 'marketing-fundamentals',
        title: 'Marketing',
        icon: Target,
        description: 'Action or business of promoting and selling products.',
        category: 'Business',
        difficulty: 'Beginner',
        tags: ['Marketing', 'Branding', 'Strategy'],
        relatedTopics: [],
        terms: [
            { term: '4 Ps', definition: 'Price, Product, Promotion, and Place - the four key elements of marketing.', example: 'Apple pricing premium (Price), innovative products (Product), sleek advertising (Promotion), retail stores (Place)' },
            { term: 'Market Segmentation', definition: 'Dividing market into distinct groups of buyers with different needs.', example: 'Car companies targeting luxury buyers vs economy buyers' },
            { term: 'Brand Equity', definition: 'Value premium that a company generates from a product with a recognizable name.', example: 'Coca-Cola brand worth billions allowing premium pricing' },
            { term: 'Customer Lifetime Value', definition: 'Predicted net profit attributed to entire future relationship with customer.', example: 'Netflix subscriber worth $1000 over 5 years at $20/month with 70% retention' },
            { term: 'Market Share', definition: 'Percentage of total sales in a market captured by a company.', example: 'iPhone having 50% of US smartphone market' }
        ]
    },
    {
        id: 'organizational-behavior',
        title: 'Org. Behavior',
        icon: Users,
        description: 'Study of human behavior in organizational settings.',
        category: 'Business',
        difficulty: 'Intermediate',
        tags: ['Organization', 'Leadership', 'Culture'],
        relatedTopics: ['management-communication'],
        terms: [
            { term: 'Corporate Culture', definition: 'The beliefs and behaviors that determine how a company\'s employees and management interact.', example: 'Google\'s innovative, open culture vs traditional hierarchy' },
            { term: 'Organizational Structure', definition: 'System defining how activities are directed toward achieving organizational aims.', example: 'Flat structure with few management levels vs hierarchical pyramid' },
            { term: 'Change Management', definition: 'Approach to transitioning individuals and organizations to a desired future state.', example: 'Managing transition from office work to remote work during COVID-19' },
            { term: 'Employee Engagement', definition: 'Level of enthusiasm and dedication an employee feels toward their job.', example: 'Measuring engagement through surveys and retention metrics' },
            { term: 'Leadership Style', definition: 'Manner and approach of providing direction and implementing plans.', example: 'Transformational leadership inspiring change vs transactional managing by tasks' }
        ]
    },
    {
        id: 'portfolio-management',
        title: 'Portfolio Mgmt',
        icon: PieChart,
        description: 'Art and science of selecting and overseeing a group of investments.',
        category: 'Investing',
        difficulty: 'Advanced',
        tags: ['Portfolio', 'Asset Allocation', 'Diversification'],
        relatedTopics: ['investments', 'investment-management'],
        terms: [
            { term: 'Asset Allocation', definition: 'Strategy that aims to balance risk and reward by apportioning a portfolio\'s assets according to an individual\'s goals.', example: '60% stocks, 30% bonds, 10% real estate based on risk tolerance' },
            { term: 'Risk Tolerance', definition: 'Degree of variability in investment returns an investor is willing to withstand.', example: 'Young investor comfortable with 100% stocks vs retiree wanting stable income' },
            { term: 'Correlation', definition: 'Statistical measure of how two securities move in relation to each other.', example: 'Gold and stocks often negatively correlated, providing diversification' },
            { term: 'Time Horizon', definition: 'Length of time an investor expects to hold an investment.', example: '30-year horizon for retirement allows more risk tolerance' },
            { term: 'Tax-Loss Harvesting', definition: 'Selling securities at a loss to offset capital gains.', example: 'Offsetting $10k gain with $10k loss to reduce taxes' },
            { term: 'Strategic Asset Allocation', definition: 'Long-term mix of assets based on expected returns and risk tolerance.', example: 'Setting 70/30 stock/bond mix and maintaining through rebalancing' }
        ]
    },
    {
        id: 'private-equity',
        title: 'Private Equity',
        icon: DollarSign,
        description: 'Capital that is not listed on a public exchange.',
        category: 'Finance',
        difficulty: 'Advanced',
        tags: ['Private Equity', 'LBO', 'Buyouts'],
        relatedTopics: ['corporate-finance', 'financial-modeling'],
        terms: [
            { term: 'LBO', definition: 'Leveraged Buyout - the acquisition of another company using a significant amount of borrowed money.', example: 'KKR buying RJR Nabisco for $25B in 1989 using mostly debt' },
            { term: 'Carried Interest', definition: 'Share of profits that general partners receive as compensation.', example: 'PE firm receiving 20% of profits above hurdle rate' },
            { term: 'EBITDA Multiple', definition: 'Valuation metric calculated as enterprise value divided by EBITDA.', example: 'Company with $100M EBITDA valued at 10x = $1B enterprise value' },
            { term: 'Management Fee', definition: 'Annual fee paid to PE firm for managing fund, typically 2% of committed capital.', example: '$1B fund charging 2% = $20M annual management fee' },
            { term: 'Hurdle Rate', definition: 'Minimum return that fund must achieve before carried interest is paid.', example: '8% hurdle rate means LPs get first 8% of returns, then 80/20 split' },
            { term: 'Capital Call', definition: 'Request for committed capital to be paid to fund.', example: 'LP committing $10M but only funding $2M initially when called' },
            { term: 'Exit Strategy', definition: 'Plan for how PE firm will realize return on investment.', example: 'IPO, strategic sale, or secondary buyout after 5-7 years' }
        ]
    },
    {
        id: 'finance-topics',
        title: 'General Finance',
        icon: Wallet,
        description: 'Broad range of finance-related subjects.',
        category: 'Finance',
        difficulty: 'Beginner',
        tags: ['Finance', 'Personal Finance', 'Basics'],
        relatedTopics: [],
        terms: [
            { term: 'Fintech', definition: 'Financial Technology - innovation that aims to compete with traditional financial methods.', example: 'Robinhood disrupting brokerage with commission-free trading' },
            { term: 'Compound Interest', definition: 'Interest calculated on initial principal and accumulated interest.', example: '$1000 at 10% annually grows to $2594 in 10 years' },
            { term: 'Time Value of Money', definition: 'Concept that money available now is worth more than the same amount in future.', example: '$100 today worth more than $100 in 1 year due to earning potential' },
            { term: 'Credit Score', definition: 'Numerical expression of creditworthiness based on credit history.', example: 'FICO score from 300-850, with 670+ considered good' },
            { term: 'Emergency Fund', definition: 'Cash reserve for unexpected expenses or income disruption.', example: '3-6 months of expenses in high-yield savings account' },
            { term: 'Yield Curve', definition: 'Line plotting yields of bonds having equal credit quality but differing maturity dates.', example: 'Inverted yield curve (short rates > long rates) often predicts recession' }
        ]
    },
    {
        id: 'behavioral-finance',
        title: 'Behavioral Finance',
        icon: Users,
        description: 'Psychological influences on financial practitioners and markets.',
        category: 'Finance',
        difficulty: 'Intermediate',
        tags: ['Psychology', 'Behavioral Economics', 'Biases'],
        relatedTopics: ['investments', 'economics'],
        terms: [
            { term: 'Loss Aversion', definition: 'The tendency to prefer avoiding losses to acquiring equivalent gains.', example: 'Feeling the pain of losing $100 twice as intensely as the joy of finding $100' },
            { term: 'Confirmation Bias', definition: 'Tendency to search for and interpret information in a way that confirms one\'s prior beliefs.', example: 'Only reading news articles that support a stock you already own' },
            { term: 'Anchoring', definition: 'Relying too heavily on the first piece of information offered (the "anchor").', example: 'Fixating on a stock\'s 52-week high and considering anything lower a "bargain" regardless of fundamentals' },
            { term: 'Herding', definition: 'Tendency for individuals to mimic the actions of a larger group.', example: 'Panic selling during a market crash just because everyone else is doing it' },
            { term: 'Mental Accounting', definition: 'Tendency to treat money differently depending on its source or intended use.', example: 'Treating a tax refund as "free money" to be spent frivolously unlike regular income' },
            { term: 'Overconfidence Effect', definition: 'Tendency to overestimate one\'s own abilities or the precision of one\'s beliefs.', example: 'Day traders believing they can consistently time the market better than professionals' },
            { term: 'Recency Bias', definition: 'Giving more weight to recent events than earlier ones.', example: 'Assuming the current bull market will continue indefinitely because the last few months were good' },
            { term: 'Gambler\'s Fallacy', definition: 'Belief that future probabilities are altered by past events.', example: 'Believing a stock is "due" to go up just because it has fallen for 5 days in a row' }
        ]
    },
    {
        id: 'quantitative-analysis',
        title: 'Quantitative Analysis',
        icon: Calculator,
        description: 'Use of mathematical and statistical modeling taking place in financial markets.',
        category: 'Finance',
        difficulty: 'Advanced',
        tags: ['Quant', 'Analysis', 'Trading', 'Statistics'],
        relatedTopics: ['financial-statement-analysis', 'investments'],
        terms: [
            { term: 'Algorithmic Trading', definition: 'Use of computer programs to execute trades at high speeds and volumes.', example: 'HFT firms making thousands of trades per second based on arbitrage opportunities' },
            { term: 'Backtesting', definition: 'Testing a predictive model on historical data.', example: 'Running a trading strategy on data from 2010-2020 to see how it would have performed' },
            { term: 'Standard Deviation', definition: 'Measure of the amount of variation or dispersion of a set of values.', example: 'Used to quantify the historical volatility of an investment' },
            { term: 'Correlation Coefficient', definition: 'Statistical measure of the strength of the relationship between the relative movements of two variables.', example: '+1.0 is perfect positive correlation, -1.0 is perfect negative correlation' },
            { term: 'Monte Carlo Simulation', definition: 'Mathematical technique used to model risk and uncertainty.', example: 'Simulating 10,000 possible future stock price paths to estimate portfolio risk' },
            { term: 'Mean Reversion', definition: 'Theory that asset prices tend to return to their long-term average.', example: 'Buying a stock when it is historically oversold, betting it will bounce back' },
            { term: 'Value at Risk (VaR)', definition: 'Statistic used to quantify the level of financial risk within a firm or portfolio.', example: '95% VaR of $1M means there is a 5% chance the portfolio loses more than $1M in a set period' },
            { term: 'R-Squared', definition: 'Statistical measure representing the proportion of the variance for a dependent variable that\'s explained by an independent variable.', example: 'R-squared of 0.85 means 85% of a fund\'s movement is explained by the index' }
        ]
    },
    {
        id: 'crypto-assets',
        title: 'Crypto Assets',
        icon: Wallet,
        description: 'Digital or virtual currencies secured by cryptography.',
        category: 'Investing',
        difficulty: 'Intermediate',
        tags: ['Cryptocurrency', 'Blockchain', 'Digital Assets'],
        relatedTopics: ['finance-topics'],
        terms: [
            { term: 'Blockchain', definition: 'Distributed ledger technology that records all transactions across a network.', example: 'Ethereum blockchain recording smart contract executions' },
            { term: 'DeFi', definition: 'Decentralized Finance - financial services on public blockchains without intermediaries.', example: 'Uniswap allowing trading without a centralized exchange' },
            { term: 'Smart Contract', definition: 'Self-executing contract with the terms of the agreement between buyer and seller being directly written into lines of code.', example: 'Automatic insurance payout when flight delay data is received' },
            { term: 'Tokenomics', definition: 'The economics of a crypto token (supply, distribution, utility).', example: 'Bitcoin\'s fixed supply cap of 21 million coins' },
            { term: 'Proof of Work', definition: 'Consensus mechanism requiring computational effort to mine blocks.', example: 'Bitcoin miners solving complex puzzles to secure the network' },
            { term: 'Proof of Stake', definition: 'Consensus mechanism where validators stake coins to create new blocks.', example: 'Ethereum 2.0 validators locking up 32 ETH' },
            { term: 'NFT', definition: 'Non-Fungible Token - unique digital identifier recorded on a blockchain.', example: 'Digital art piece sold as a unique asset' },
            { term: 'Stablecoin', definition: 'Cryptocurrency designed to have a relatively stable price, typically pegged to a commodity or currency.', example: 'USDC pegged 1:1 to the US Dollar' }
        ]
    },
    {
        id: 'supply-chain',
        title: 'Supply Chain',
        icon: Globe,
        description: 'Management of the flow of goods and services.',
        category: 'Business',
        difficulty: 'Intermediate',
        tags: ['Supply Chain', 'Operations', 'Logistics'],
        relatedTopics: [],
        terms: [
            { term: 'Just-in-Time (JIT)', definition: 'Inventory strategy to increase efficiency by receiving goods only as they are needed.', example: 'Toyota receiving car parts hours before assembly' },
            { term: 'Bullwhip Effect', definition: 'Phenomenon where small fluctuations in demand at the retail level cause progressively larger fluctuations at the wholesale and manufacturer levels.', example: 'Panic buying of toilet paper causing massive overproduction orders' },
            { term: 'Logistics', definition: 'Detailed organization and implementation of a complex operation.', example: 'Amazon optimizing delivery routes for millions of packages' },
            { term: 'Procurement', definition: 'Process of finding and agreeing to terms, and acquiring goods or services.', example: 'Negotiating contracts with raw material suppliers' },
            { term: 'Freight Forwarder', definition: 'Person or company that organizes shipments for individuals or corporations.', example: 'Company handling customs and shipping for importing electronics from Asia' },
            { term: 'Last Mile Delivery', definition: 'Movement of goods from a transportation hub to the final delivery destination.', example: 'Delivery driver bringing package to your doorstep' }
        ]
    },
    {
        id: 'financial-modeling',
        title: 'Financial Modeling',
        icon: Building,
        description: 'Summary of a company\'s expenses and earnings in a spreadsheet.',
        category: 'Finance',
        difficulty: 'Advanced',
        tags: ['Modeling', 'Valuation', 'DCF'],
        relatedTopics: ['corporate-finance', 'financial-statement-analysis'],
        terms: [
            { term: 'DCF', definition: 'Discounted Cash Flow - a valuation method used to estimate the value of an investment based on its expected future cash flows.', example: 'Projecting 5 years of free cash flows and discounting to present value at WACC' },
            { term: 'Three Statement Model', definition: 'Financial model linking income statement, balance sheet, and cash flow statement.', example: 'Net income flowing to equity, driving cash and retained earnings' },
            { term: 'Sensitivity Analysis', definition: 'Analyzing how changes in assumptions affect model outputs.', example: 'Testing valuation impact of revenue growth from 5% to 15%' },
            { term: 'Scenario Analysis', definition: 'Evaluating outcomes under different sets of assumptions.', example: 'Base case, bull case, and bear case valuation scenarios' },
            { term: 'Terminal Value', definition: 'Value of business beyond explicit forecast period.', example: 'Using perpetuity growth method: Final FCF × (1+g) / (WACC - g)' },
            { term: 'Monte Carlo Simulation', definition: 'Using repeated random sampling to model probability of different outcomes.', example: 'Running 10,000 simulations to estimate range of possible stock prices' },
            { term: 'Waterfall Analysis', definition: 'Showing how value flows from enterprise value to equity holders.', example: 'Enterprise Value minus Net Debt = Equity Value' },
            { term: 'LBO Model', definition: 'Model used to evaluate the acquisition of a company using a significant amount of debt.', example: 'Calculating IRR for a private equity buyout' },
            { term: 'M&A Model', definition: 'Accretion/Dilution analysis to determine the impact of an acquisition on earnings per share.', example: 'Determining if buying a competitor will increase EPS' }
        ]
    }
];
